Repository temple2018/Galaxia, pull requests merged in 2018-07, with the labels that each got.

#12 Fix the Demuxing
  src/main/java/org/templegalaxia/DemuxArtNetDatagram.java
Labels: bug

#13 Ew print statement
  src/main/java/org/templegalaxia/DemuxArtNetDatagram.java
Labels: Reviewer can merge, enhancement

#14 SemiDemuxed Fixture
  src/main/java/org/templegalaxia/GalaxiaGui.java
  src/main/java/org/templegalaxia/datagrams/MultiplexedArtNet.java
  src/main/java/org/templegalaxia/datagrams/SemiMultiplexedArtNet.java
Labels: enhancement

#21 Rings v3
  .gitignore
  src/main/java/org/templegalaxia/GalaxiaGui.java
  src/main/java/org/templegalaxia/model/Petal.java
  src/main/java/org/templegalaxia/model/Ring.java
  src/main/java/org/templegalaxia/model/Temple.java
  src/main/java/org/templegalaxia/patterns/TemplePattern.java
  src/main/java/org/templegalaxia/patterns/gerald/PetalChase.java
  src/main/java/org/templegalaxia/patterns/ted/RingTest.java
Labels: Model, enhancement

#23 Add the floor point resource
  src/main/java/org/templegalaxia/model/Petal.java
  src/main/resources/org/templegalaxia/model/floorPoints.csv
  src/main/resources/org/templegalaxia/model/petalPoints.csv
Labels: Model
